[workspace]
resolver = "3"
members = [
	"bencode",
	"core", 
	"cli", 
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = [
	"Nikita Doronin (duckysmacky)",
	"Grigoriy Agasyants (shroomwastaken)"
]
repository = "https://github.com/duckysmacky/jigsaw"

[workspace.dependencies]
jigsaw-bencode = { version = "0.1.0", path = "./bencode" }
jigsaw-core = { version = "0.1.0", path = "./core" }
